type System {
  id: Int
  name: String
  team: String
  details: String
  icon: String
  isAlive: Boolean
  lastAlive: String
  url: String
}

input SystemInput {
  id: Int
  name: String
  team: String
  details: String
  icon: String
  isAlive: Boolean
  lastAlive: String
  url: String
}

extend type Query {
  getSystems(reality: Int): [System]
}

extend type Mutation {
  addSystem(reality: Int, data: SystemInput): [System]
  updateSystem(reality: Int, data: SystemInput): [System]
  removeSystem(reality: Int, id: Int): Int
}